dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: molecule-disk-test:latest
    dockerfile: Dockerfile.j2
    privileged: true
    command: /bin/bash -c "while true; do sleep 1000; done"
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
